on: [push, pull_request]

env:
  CONAN_USE_DOCKER: 1
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}

jobs:
  Gcc:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        version: ["4.9", "5", "6", "7", "8", "9"]
    env:
      CONAN_GCC_VERSIONS: ${{matrix.version}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Conan
        run: |
          pip install conan
          conan user
      - name: Install libsecret and other dependencies
        # Only libsecret is required for building the package. However, the test-package needs an
        # actual keyring.
        run: |
          sudo apt-get update
          sudo apt-get install libsecret-1-dev dbus-x11 dbus gnome-keyring libgnome-keyring-dev
      - name: Run
        run: |
            # steps required to setup the keyring
            export DISPLAY=:99.0
            eval $(dbus-launch --sh-syntax)
            echo '$(whoami)' | gnome-keyring-daemon -r -d --unlock
            # build the package and test-package
            conan create . keychain/1.1@ --build missing

  Clang:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        version: ["3.9", "4.0", "5.0", "6.0", "7.0", "8", "9"]
    env:
      CONAN_CLANG_VERSIONS: ${{matrix.version}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Conan
        run: |
          pip install conan
          conan user
      - name: Install libsecret and other dependencies
        # Only libsecret is required for building the package. However, the test-package needs an
        # actual keyring.
        run: |
          sudo apt-get update
          sudo apt-get install libsecret-1-dev dbus-x11 dbus gnome-keyring libgnome-keyring-dev
      - name: Run
        run: |
            # steps required to setup the keyring
            export DISPLAY=:99.0
            eval $(dbus-launch --sh-syntax)
            echo '$(whoami)' | gnome-keyring-daemon -r -d --unlock
            # build the package and test-package
            conan create . keychain/1.1@ --build missing
